require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::PublicitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Publicity. As you add validations to Admin::Publicity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::PublicitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_publicities as @admin_publicities" do
      publicity = Admin::Publicity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_publicities).should eq([publicity])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_publicity as @admin_publicity" do
      publicity = Admin::Publicity.create! valid_attributes
      get :show, {:id => publicity.to_param}, valid_session
      assigns(:admin_publicity).should eq(publicity)
    end
  end

  describe "GET new" do
    it "assigns a new admin_publicity as @admin_publicity" do
      get :new, {}, valid_session
      assigns(:admin_publicity).should be_a_new(Admin::Publicity)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_publicity as @admin_publicity" do
      publicity = Admin::Publicity.create! valid_attributes
      get :edit, {:id => publicity.to_param}, valid_session
      assigns(:admin_publicity).should eq(publicity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Publicity" do
        expect {
          post :create, {:admin_publicity => valid_attributes}, valid_session
        }.to change(Admin::Publicity, :count).by(1)
      end

      it "assigns a newly created admin_publicity as @admin_publicity" do
        post :create, {:admin_publicity => valid_attributes}, valid_session
        assigns(:admin_publicity).should be_a(Admin::Publicity)
        assigns(:admin_publicity).should be_persisted
      end

      it "redirects to the created admin_publicity" do
        post :create, {:admin_publicity => valid_attributes}, valid_session
        response.should redirect_to(Admin::Publicity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_publicity as @admin_publicity" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publicity.any_instance.stub(:save).and_return(false)
        post :create, {:admin_publicity => { "title" => "invalid value" }}, valid_session
        assigns(:admin_publicity).should be_a_new(Admin::Publicity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publicity.any_instance.stub(:save).and_return(false)
        post :create, {:admin_publicity => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_publicity" do
        publicity = Admin::Publicity.create! valid_attributes
        # Assuming there are no other admin_publicities in the database, this
        # specifies that the Admin::Publicity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Publicity.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => publicity.to_param, :admin_publicity => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_publicity as @admin_publicity" do
        publicity = Admin::Publicity.create! valid_attributes
        put :update, {:id => publicity.to_param, :admin_publicity => valid_attributes}, valid_session
        assigns(:admin_publicity).should eq(publicity)
      end

      it "redirects to the admin_publicity" do
        publicity = Admin::Publicity.create! valid_attributes
        put :update, {:id => publicity.to_param, :admin_publicity => valid_attributes}, valid_session
        response.should redirect_to(publicity)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_publicity as @admin_publicity" do
        publicity = Admin::Publicity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publicity.any_instance.stub(:save).and_return(false)
        put :update, {:id => publicity.to_param, :admin_publicity => { "title" => "invalid value" }}, valid_session
        assigns(:admin_publicity).should eq(publicity)
      end

      it "re-renders the 'edit' template" do
        publicity = Admin::Publicity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Publicity.any_instance.stub(:save).and_return(false)
        put :update, {:id => publicity.to_param, :admin_publicity => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_publicity" do
      publicity = Admin::Publicity.create! valid_attributes
      expect {
        delete :destroy, {:id => publicity.to_param}, valid_session
      }.to change(Admin::Publicity, :count).by(-1)
    end

    it "redirects to the admin_publicities list" do
      publicity = Admin::Publicity.create! valid_attributes
      delete :destroy, {:id => publicity.to_param}, valid_session
      response.should redirect_to(admin_publicities_url)
    end
  end

end
