development: &default
  username: agro.social2-facilitator_api1.gmail.com
  password: 1389029188
  signature: ABD1raCJJwUbdn0bSZKBZGDyMTypAauEmm5xWYssPtqSgOxAmHFGC592
  app_id: APP-2RX55952G68472502
  http_timeout: 30
  mode: sandbox
  sandbox_email_address: agro.social2-facilitator@gmail.com
  # # with certificate
  # cert_path: "config/cert_key.pem"
  # # with token authentication
  # token: ESTy2hio5WJQo1iixkH29I53RJxaS0Gvno1A6.YQXZgktxbY4I2Tdg
  # token_secret: ZKPhUYuwJwYsfWdzorozWO2U9pI
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with device ip address
  # device_ipaddress: "127.0.0.1"
test:
  <<: *default
production:
  mode: live
  username: USERNAME
  password: PASSWORD
  signature: SIGNATURE
  app_id: APP_ID