require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Academy::WorkshopRegistrationsController do

  # This should return the minimal set of attributes required to create a valid
  # Academy::WorkshopRegistration. As you add validations to Academy::WorkshopRegistration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "workshop_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Academy::WorkshopRegistrationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all academy_workshop_registrations as @academy_workshop_registrations" do
      workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:academy_workshop_registrations).should eq([workshop_registration])
    end
  end

  describe "GET show" do
    it "assigns the requested academy_workshop_registration as @academy_workshop_registration" do
      workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
      get :show, {:id => workshop_registration.to_param}, valid_session
      assigns(:academy_workshop_registration).should eq(workshop_registration)
    end
  end

  describe "GET new" do
    it "assigns a new academy_workshop_registration as @academy_workshop_registration" do
      get :new, {}, valid_session
      assigns(:academy_workshop_registration).should be_a_new(Academy::WorkshopRegistration)
    end
  end

  describe "GET edit" do
    it "assigns the requested academy_workshop_registration as @academy_workshop_registration" do
      workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
      get :edit, {:id => workshop_registration.to_param}, valid_session
      assigns(:academy_workshop_registration).should eq(workshop_registration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Academy::WorkshopRegistration" do
        expect {
          post :create, {:academy_workshop_registration => valid_attributes}, valid_session
        }.to change(Academy::WorkshopRegistration, :count).by(1)
      end

      it "assigns a newly created academy_workshop_registration as @academy_workshop_registration" do
        post :create, {:academy_workshop_registration => valid_attributes}, valid_session
        assigns(:academy_workshop_registration).should be_a(Academy::WorkshopRegistration)
        assigns(:academy_workshop_registration).should be_persisted
      end

      it "redirects to the created academy_workshop_registration" do
        post :create, {:academy_workshop_registration => valid_attributes}, valid_session
        response.should redirect_to(Academy::WorkshopRegistration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved academy_workshop_registration as @academy_workshop_registration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Academy::WorkshopRegistration.any_instance.stub(:save).and_return(false)
        post :create, {:academy_workshop_registration => { "workshop_id" => "invalid value" }}, valid_session
        assigns(:academy_workshop_registration).should be_a_new(Academy::WorkshopRegistration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Academy::WorkshopRegistration.any_instance.stub(:save).and_return(false)
        post :create, {:academy_workshop_registration => { "workshop_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested academy_workshop_registration" do
        workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
        # Assuming there are no other academy_workshop_registrations in the database, this
        # specifies that the Academy::WorkshopRegistration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Academy::WorkshopRegistration.any_instance.should_receive(:update).with({ "workshop_id" => "1" })
        put :update, {:id => workshop_registration.to_param, :academy_workshop_registration => { "workshop_id" => "1" }}, valid_session
      end

      it "assigns the requested academy_workshop_registration as @academy_workshop_registration" do
        workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
        put :update, {:id => workshop_registration.to_param, :academy_workshop_registration => valid_attributes}, valid_session
        assigns(:academy_workshop_registration).should eq(workshop_registration)
      end

      it "redirects to the academy_workshop_registration" do
        workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
        put :update, {:id => workshop_registration.to_param, :academy_workshop_registration => valid_attributes}, valid_session
        response.should redirect_to(workshop_registration)
      end
    end

    describe "with invalid params" do
      it "assigns the academy_workshop_registration as @academy_workshop_registration" do
        workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Academy::WorkshopRegistration.any_instance.stub(:save).and_return(false)
        put :update, {:id => workshop_registration.to_param, :academy_workshop_registration => { "workshop_id" => "invalid value" }}, valid_session
        assigns(:academy_workshop_registration).should eq(workshop_registration)
      end

      it "re-renders the 'edit' template" do
        workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Academy::WorkshopRegistration.any_instance.stub(:save).and_return(false)
        put :update, {:id => workshop_registration.to_param, :academy_workshop_registration => { "workshop_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested academy_workshop_registration" do
      workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
      expect {
        delete :destroy, {:id => workshop_registration.to_param}, valid_session
      }.to change(Academy::WorkshopRegistration, :count).by(-1)
    end

    it "redirects to the academy_workshop_registrations list" do
      workshop_registration = Academy::WorkshopRegistration.create! valid_attributes
      delete :destroy, {:id => workshop_registration.to_param}, valid_session
      response.should redirect_to(academy_workshop_registrations_url)
    end
  end

end
